drop table if exists album CASCADE;
drop table if exists album_authorship CASCADE;
drop table if exists artist CASCADE;
drop table if exists genre CASCADE;
drop table if exists playlist CASCADE;
drop table if exists song CASCADE;
drop table if exists song_authorship CASCADE;
drop table if exists song_by_playlist CASCADE;

create table album
(
    id    bigint generated by default as identity,
    title varchar(255),
    primary key (id)
);
create table album_authorship
(
    artists_id bigint not null,
    albums_id  bigint not null
);
create table artist
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table genre
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table playlist
(
    id    bigint generated by default as identity,
    title varchar(255),
    primary key (id)
);
create table song
(
    id       bigint generated by default as identity,
    title    varchar(255),
    album_id bigint,
    genre_id bigint,
    primary key (id)
);
create table song_authorship
(
    artists_id bigint not null,
    songs_id   bigint not null
);
create table song_by_playlist
(
    playlists_id bigint not null,
    songs_id     bigint not null
);

alter table album_authorship
    add constraint fk_album_album_authorship foreign key (albums_id) references album;
alter table album_authorship
    add constraint fk_artist_album_authorship foreign key (artists_id) references artist;
alter table song
    add constraint FKrcjmk41yqj3pl3iyii40niab0 foreign key (album_id) references album;
alter table song
    add constraint FK3kr980xhy18ojchq1ekbevypy foreign key (genre_id) references genre;
alter table song_authorship
    add constraint fk_song_song_authorship foreign key (songs_id) references song;
alter table song_authorship
    add constraint fk_artist_song_authorship foreign key (artists_id) references artist;
alter table song_by_playlist
    add constraint fk_song_song_by_playlist foreign key (songs_id) references song;
alter table song_by_playlist
    add constraint fk_playlist_song_by_playlist foreign key (playlists_id) references playlist;